### ISSUE TITLE
new API's to include

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/clc-go-cli#33]
please put these in the CLI
https://www.ctl.io/api-docs/v2/#groups-set-group-horizontal-autoscale-policy
https://www.ctl.io/api-docs/v2/#groups-get-group-horizontal-autoscale-policy
https://www.ctl.io/api-docs/v2/#groups-get-group-scheduled-activities
https://www.ctl.io/api-docs/v2/#groups-set-group-defaults

**Comment by ldmberman** [comment]
The last [one](https://www.ctl.io/api-docs/v2/#groups-set-group-defaults) seems to be broken now - the server responds with `405 Method Not Allowed`. I've reported it to the support.

**Comment by ldmberman** [comment]
@chrislittle the commands have been added, please, check the [latest release](https://github.com/CenturyLinkCloud/clc-go-cli/releases/tag/2015-10-29).
