### ISSUE TITLE
delete load balancer case-sensitive

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/clc-go-cli#34]
C:\clc>clc load-balancer delete --data-center DE1 --load-balancer-name test --profile sandbox
There are no load balancers with name test in DE1.

C:\clc>clc load-balancer delete --data-center DE1 --load-balancer-name Test --profile sandbox

job completes.  is the code supposed to be (for LB name) case sensitive?  

also test the action as for me the CLI never went back to the cmd prompt until i hit enter, like it was stuck

**Comment by ldmberman** [comment]
Yes, I believe LB names are supposed to be case-sensitive - the server retains the case.

> also test the action as for me the CLI never went back to the cmd prompt until i hit enter, like it was stuck

For how long had you been waiting for the command to complete? I am not able to reproduce the issue.

**Comment by chrislittle** [comment]
thx if its supposed to be that way i'm good.  i can't reproduce the issue anymore either. perhaps it was a temp api issue. closing
