### ISSUE TITLE
CLI Doesn't appear to be working on Mac OS

### ISSUE THREAD

**Issue by idrabenia** [CenturyLinkCloud/clc-go-cli#36]
Hi, guys. I've tried to install clc on my MacBook using links from README, but it didn't worked for me. Here is what I have in my terminal:

```
Ilyas-MacBook-Pro:tmp idrabenia$ clc login --user name --password xxx
Logged in as name.
Ilyas-MacBook-Pro:tmp idrabenia$ clc server list
DataCenter: non zero value required
Ilyas-MacBook-Pro:tmp idrabenia$ CLC_TRACE=true clc server list
DataCenter: non zero value required
Ilyas-MacBook-Pro:tmp idrabenia$ CLC_DEBUG=true clc server list
DataCenter: non zero value required
```

**Comment by chrislittle** [comment]
once logged in you'd input:

```
clc server list --data-center WA1
```

if you want to set a default data center you can can do so using

```
clc data-center set-default --data-center WA1
```

then you could do a normal server list for that default without the --data-center tag

**Comment by idrabenia** [comment]
@chrislittle thank you for answer.

I am sure that in this case the error message could be more informative. I believe it will help end users.

Do you think the CLI could ask for unknown values interactively if they absent ?

**Comment by chrislittle** [comment]
I'd file an issue in github and see if the developers will evaluate the request.  if you want to see the required fields in the mean time you can use --help on any command in the tree.

```
clc server list --help 
```

```
clc server --help
```

```
clc server update --help
```

just some examples.  but the --help always shows what is required vs optional and I find it quite helpful.

**Comment by chrislittle** [comment]
and also there is a 

```
clc server list --all
```

if you want everything.....

**Comment by ldmberman** [comment]
Hi @idrabenia,

> Do you think the CLI could ask for unknown values interactively if they absent ?

It is actually asking you for one of those:

> DataCenter: non zero value required

The letter case and the error message may be confusing though. The former is originally there because of the possibility to specify it this way in JSON:

```
clc server list '{"DataCenter":"WA1"}'
```

Perhaps, it would make sense to only allow the dashed way (`data-center`) of writing property names.

The error message could also be like `The data-center field must be set and non-empty`. @chrislittle?

**Comment by chrislittle** [comment]
you could definitely do the "The data-center field must be set and non-empty" .  If this was consistent across all commands that are required and missed by a user it would probably make the error more friendly.

**Comment by jruckle** [comment]
@ldmberman can you make this enhancement?

**Comment by ldmberman** [comment]
Please, see [the latest release](https://github.com/CenturyLinkCloud/clc-go-cli/releases/tag/2016-01-06).

**Comment by jruckle** [comment]
@ldmberman is this OK to close?
