### ISSUE TITLE
The example queries need capitalizing names

### ISSUE THREAD

**Issue by gavin-lai** [CenturyLinkCloud/clc-go-cli#40]
Hi, 
I ran the examples on https://github.com/CenturyLinkCloud/clc-go-cli as demo and realized the names of the queries are in lower cases, which would give errors, like templates.name (templates.name: there is no such field in the result), id.  After removing the query from the command, the output shows that the query names need to capitalize the first letter.  Is this by design or both lower and upper case name should work?
Some of the commands ran are:
clc data-center get-deployment-capabilities --data-center <data-center> --query templates.name --output text
clc group list --all --filter location-id=<data-center> --query id --output text
I verified the behaviours in both Windows and CentOS are the same.  I am running clc-2015-11-06-windows-x64.zip and clc-2015-11-06-linux-amd64.tar.gz binary.
Thanks
Gavin

**Comment by ldmberman** [comment]
Both cases should work - I am going to fix this.

**Comment by ldmberman** [comment]
Please, try [the latest release](https://github.com/CenturyLinkCloud/clc-go-cli/releases/tag/2016-01-06).
