### ISSUE TITLE
new APIs

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/clc-go-cli#41]
some new API's to get into the CLI
https://www.ctl.io/api-docs/v2/#groups-set-group-scheduled-activities

IPS API
https://www.ctl.io/knowledge-base/security/ips-api/

**Comment by jruckle** [comment]
@ldmberman can you add these to the CLI?

**Comment by ldmberman** [comment]
I've added the first one in [the latest release](https://github.com/CenturyLinkCloud/clc-go-cli/releases/tag/2016-01-06).

**Comment by ldmberman** [comment]
@chrislittle @jruckle The IPS support has been added in [the latest release](https://github.com/CenturyLinkCloud/clc-go-cli/releases/tag/2016-03-28).
