### ISSUE TITLE
api change

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/clc-go-cli#42]
https://www.ctl.io/api-docs/v2/#servers-get-server

new string:
displayName	string	Friendly display name for the server (can be the same as the name)

it doesn't appear in any create API's but wanted you to know its there now.

**Comment by ldmberman** [comment]
@chrislittle I've added it [in the latest release](https://github.com/CenturyLinkCloud/clc-go-cli/releases/tag/2016-03-28).
