### ISSUE TITLE
relational db APIs

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/clc-go-cli#43]
we have now launched our relationdb mysql service.  please get the API's into the CLI for managing this service.

service: https://www.ctl.io/relational-database/

APIs:  https://api.rdbs.ctl.io/api/swagger/index.html

**Comment by ldmberman** [comment]
@jruckle @chrislittle done; please, see [the latest release](https://github.com/CenturyLinkCloud/clc-go-cli/releases/tag/2016-03-28)
