### ISSUE TITLE
Remove case sensitivity from specifying servers with GoCLI

### ISSUE THREAD

**Issue by russmalloy** [CenturyLinkCloud/clc-go-cli#45]
The server name and Network name (and possibly account alias) are case sensitive when running the commands used when adding secondary nics.

https://www.ctl.io/knowledge-base/network/add-or-remove-network-interface-to-server-using-go-cli/

I've put in a PM request to update documentation for this, but it seems like removing case sensitivity would be worthwhile from the commands as well.

**Comment by ldmberman** [comment]
@russmalloy thank you for pointing this out.

As far as I see, the same applies for the server, network, group, and load-balancer names in all of the commands. I've fixed it so you can give it a try with [the latest release](https://github.com/CenturyLinkCloud/clc-go-cli/releases/tag/2016-03-28).

**Comment by chrislittle** [comment]
tested/confirmed @russmalloy please close this issue

**Comment by jruckle** [comment]
Closing
