### ISSUE TITLE
Custom field

### ISSUE THREAD

**Issue by gavin-lai** [CenturyLinkCloud/clc-go-cli#46]
Good afternoon,
The current support for custom field is only for id and value, would it be expand to include 'isRquired', type and name?
Thanks
Gavin

**Comment by ldmberman** [comment]
@jruckle @gavin-lai was updated in [the latest release](https://github.com/CenturyLinkCloud/clc-go-cli/releases/tag/2016-03-28)

**Comment by jruckle** [comment]
Closing
