### ISSUE TITLE
Snapshot ID in clc get server output?

### ISSUE THREAD

**Issue by gavin-lai** [CenturyLinkCloud/clc-go-cli#48]
Good afternoon,
A few customers are asking ways to schedule creation and deletion in a regular interval, in order to delete a snapshot, the delete-snapshot command requires the snapshot ID.  The Snapshot ID is not part of the get server output: (for example)
clc server get --server-name CA3CCVA2TAKE02
The snapshot output:
{
    "Snapshots": [
        {
            "Name": "2016-03-29.19:54:14"
        }
    ]
}
It will give me the snapshot creation date, not the snapshot ID under details.snapshots.links
I can see the snapshot ID in the trace as below:
"snapshots":[{"name":"2016-03-29.19:54:14","links":[{"rel":"self","href":"/v2/servers/ccva/ca3ccva2take02/snapshots/157"},{"rel":"delete","href":"/v2/servers/ccva/ca3ccva2take02/snapshots/157"}
The snapshot ID is 157.
Is there a way to get the snapshot ID from the clc output to help scripting the creation and deletion of the snapshot?  
Thanks
Gavin

**Comment by ldmberman** [comment]
@gavin-lai done; please, see [the latest release](https://github.com/CenturyLinkCloud/clc-go-cli/releases/tag/2016-03-30)

**Comment by gavin-lai** [comment]
Thank you for the quick fix.
