### ISSUE TITLE
include simple backup API in CLI

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/clc-go-cli#49]
simple backup is now live please include in the CLI
https://www.ctl.io/simple-backup-service/

APIs:  https://api-va1.backup.ctl.io/clc-backup-api/swagger-ui.html

separate from this as backup, IPS, dbaas evolve how should we keep things updating? iterations are coming fast and furious......

**Comment by chrislittle** [comment]
@jruckle see the last comment in this.  how do we keep the CLI teams updated on features in various products

**Comment by jruckle** [comment]
@chrislittle there is probably some discretion about what APIs we want to support in the tool - so I think just continue to flag them here as issues, and then we can work with the team to prioritize. if Backup is something that makes sense, let's get it on the backlog.

**Comment by chrislittle** [comment]
sure the big items right now are creating a policy, disabling a policy, applying and removing policies from servers i'd think.  since via the gui you have to do 1 by 1 and its painful @jruckle large clients are really saying "I have to spend hours clicking this"  not great

**Comment by jruckle** [comment]
@ldmberman can you provide an estimate for this work?

**Comment by ldmberman** [comment]
@chrislittle @jruckle an initial version has been implemented [here](https://github.com/CenturyLinkCloud/clc-go-cli/releases/tag/2016-04-06). Some updates might be needed soon after some of the [1](https://support.ctl.io/hc/en-us/requests/1252244), [2](https://support.ctl.io/hc/en-us/requests/1252247), [3](https://support.ctl.io/hc/en-us/requests/1252625) are resolved.

**Comment by chrislittle** [comment]
sounds good.  I'm not going to really talk about this integration until some of these items are solved.

**Comment by chrislittle** [comment]
@ldmberman it appears the --account-alias option doesn't work on backup calls for sub accounts.  

```
clc backup get-account-policies --profile demo --account-alias ACMC
```

it doesn't give me anything but a list of policies in the ACMC alias parent (CCCD).  

```
{
    "Limit": 1000,
    "NextOffset": 0,
    "Offset": 0,
    "Results": [
        {
            "BackupIntervalHours": 24,
            "ClcAccountAlias": "CCCD",
            "ExcludedDirectoryPaths": [],
            "Name": "Web Servers",
            "OsType": "Windows",
            "Paths": [
                "C:\\inetpub\\wwwroot"
            ],
            "PolicyId": "d4c3ad30-6d8f-4c7e-97c2-295ac78ddf3e",
            "RetentionDays": 7,
            "Status": "ACTIVE"
        },
        {
            "BackupIntervalHours": 24,
            "ClcAccountAlias": "CCCD",
            "ExcludedDirectoryPaths": [],
            "Name": "SQL Servers",
            "OsType": "Windows",
            "Paths": [
                "C:\\Program Files\\Microsoft SQL Server\\MSSQL12.MSSQLSERVER\\MSSQL\\Backup"
            ],
            "PolicyId": "5ad8c9a6-7288-452c-bf88-f279f05294c0",
            "RetentionDays": 7,
            "Status": "ACTIVE"
        },
        {
            "BackupIntervalHours": 24,
            "ClcAccountAlias": "CCCD",
            "ExcludedDirectoryPaths": [
                "F:\\"
            ],
            "Name": "doghouse backup",
            "OsType": "Windows",
            "Paths": [
                "E:\\",
                "H:\\"
            ],
            "PolicyId": "e7d852d0-c641-4887-92a7-b96cb0143718",
            "RetentionDays": 365,
            "Status": "INACTIVE"
        },
        {
            "BackupIntervalHours": 24,
            "ClcAccountAlias": "CCCD",
            "ExcludedDirectoryPaths": [],
            "Name": "Web Demo",
            "OsType": "Linux",
            "Paths": [
                "/xvdf"
            ],
            "PolicyId": "8742b1b0-c5a2-45c9-a4fb-4ce14ea42608",
            "RetentionDays": 30,
            "Status": "INACTIVE"
        },
        {
            "BackupIntervalHours": 1,
            "ClcAccountAlias": "CCCD",
            "ExcludedDirectoryPaths": [],
            "Name": "IIS Server Data Drive",
            "OsType": "Windows",
            "Paths": [
                "D:\\"
            ],
            "PolicyId": "2a4872ac-eaca-461a-889f-2179cedfc7c5",
            "RetentionDays": 90,
            "Status": "INACTIVE"
        },
        {
            "BackupIntervalHours": 48,
            "ClcAccountAlias": "CCCD",
            "ExcludedDirectoryPaths": [
                "F:\\"
            ],
            "Name": "doghouse2",
            "OsType": "Windows",
            "Paths": [
                "D:\\"
            ],
            "PolicyId": "50e49054-3ae2-4a8e-9cf2-a7865a7f618a",
            "RetentionDays": 3000,
            "Status": "INACTIVE"
        }
    ],
    "TotalCount": 6
}
```

@joonpark

**Comment by jruckle** [comment]
@ldmberman - can you comment on the status here?

**Comment by uzzz** [comment]
I took a look at issue with account alias filtering: API does not support filtering by account alias. Of course I can filter it on the CLI side, but it will break TotalCount, Limit and Offset features.

**Comment by chrislittle** [comment]
i'll log a feature as this should be in the api

**Comment by chrislittle** [comment]
feature opened https://t3n.zendesk.com/agent/tickets/1289630 and copied @ryanbrockman

**Comment by JonTaitCtl** [comment]
You can add "CLC-ALIAS" header in your request with a value of "ACMC" for the example given above to impersonate the ACMC account when using a bearer token for CCCD. I hope that addresses the issue.

**Comment by uzzz** [comment]
Thanks @JonTaitCtl
