### ISSUE TITLE
output to csv

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/clc-go-cli#51]
is there a way we could create a default output to csv for the CLI?  we have TAMs (account mgrs) using the tool and being able to output to csv native would really help them.

**Comment by ldmberman** [comment]
If it is something simple of a form:
```
[
  {
    "key1": "value11",
    "key2": "value12"
  },
  {
    "key1": "value21",
    "key2": "value22"
  }
]
```

then it might be convenient to use [jq](https://stedolan.github.io/jq/):

```
jq 'map(keys)[0], (map(to_entries) | .[] | map(.value)) | @csv' my.json
```

If it is a complex deeply nested structure like a `clc group list` output then csv is far from being the most friendly way to display such information.

Anyway, it's not very hard to implement native csv formatting. The only question is how to render nested objects. Would JSON work?

**Comment by gavin-lai** [comment]
Lots of users are looking for csv output for ease of data manipulation in spreadsheet, is it possible to have and output option as csv (like text, json, table)?  For nested output, as long as there is a delimiter, I think the users can figure a way to make it work in spreadsheet.

**Comment by ldmberman** [comment]
@gavin-lai sure, it's possible. I don't get your point about the nested output, is JSON ok?

**Comment by gavin-lai** [comment]
JSON is ok as default output, if someone wants the same output in csv, would they get the same data with delimiters?

**Comment by flxstr** [comment]
Understand your question about nested, can this be resolved by always having a parent alias column in the output? What nested items would not have parent alias that would need consideration?

**Comment by gavin-lai** [comment]
Yes, it can be resolved by parent alias column, like the table output

**Comment by ldmberman** [comment]
@flxstr yes, it would work for the nested objects but what if we have a nested array of objects? Should we display the values of the additional columns comma-separated within the cell? Should we do the same for the lists of strings, ints, etc?

**Comment by ldmberman** [comment]
@gavin-lai we do not have parent aliases in table output - we have nested tables, unless I failed to get what you mean by parent aliases

**Comment by gavin-lai** [comment]
Oh, I mean the name of the value, like the heading of a table.  Do you have an example of nested array output?

**Comment by gavin-lai** [comment]
I think we should delimit strings and ints as long as they are separate data points.

**Comment by ldmberman** [comment]
@gavin-lai let's consider the following example:

```
[
  {
    "array": [
      {
        "outerKey": "value",
        "nestedArray": [
          {
            "innerKey1": "value11",
            "innerKey2": "value12"
          },
          {
            "innerKey1": "value21",
            "innerKey2": "value22"
          }
        ]
      }
    ],
    "listOfStrings": ["1", "2", "3"]
  }
]
```

Should we convert it to:

```
"array.outerKey","array.nestedArray.innerKey1","array.nestedArray.innerKey2","listOfStrings"
"value","value11,value21","value12,value22","1,2,3"
```
?

**Comment by gavin-lai** [comment]
That looks good.

**Comment by jruckle** [comment]
@ldmberman  - can you update status here?
