### ISSUE TITLE
Running under the SYSTEM account in Windows

### ISSUE THREAD

**Issue by gavin-lai** [CenturyLinkCloud/clc-go-cli#53]
A customer is scheduling a task using the CLI and it fails when using the SYSTEM account, even when passing the user name and password in line, the details from the client below:

Yes, and using the default settings (which launch the process under the user account that was used to create the task), it initially works.  However, if you were to edit the properties of this task, click “Change User or Group…”, type “SYSTEM”, click OK, click OK again, and run the task again, you’ll see it fail with the same error we get under SQLAgent.  This is because the SYSTEM account lacks a profile/home directory altogether, which is what seems to cause the go-based clc.exe application to fail with the error no matter what we try to do.  Here’s a bat file I used to test and verify this with the Windows Task Scheduler:

@echo off

REM -- Settings (Note that a double-percent character is used to escape a single percent character.)
SET CLC_EXE="C:\Development\clc-cli\clc.exe"
SET CLC_TEMP_FILE="C:\Development\clc-cli\temp.txt"
SET CLCUSR=REDACTED
SET CLCPWD=REDACTED

echo "" > %CLC_TEMP_FILE%
%CLC_EXE% server list --data-center IL1 --output table --user %CLCUSR% --password %CLCPWD% 1> %CLC_TEMP_FILE% 2>&1

…The same behavior also occurs when renaming CLCUSR to CLC_USER and CLCPWD to CLC_PASSWORD and removing the --user and --password arguments (which works when run under my user account, which of course has a profile directory).

Do we somehow need the clc\config.yml file to run the CLI?
Thanks
Gavin

**Comment by jruckle** [comment]
@ldmberman  - can you review and comment?
