### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/clc-go-cli#54]
@jruckle 

we'd like cross DC API added to CLI
https://www.ctl.io/api-docs/v2/#firewall-policies-create-a-cross-data-center-firewall-policy
https://www.ctl.io/api-docs/v2/#firewall-policies-delete-a-cross-data-center-firewall-policy
https://www.ctl.io/api-docs/v2/#firewall-policies-get-cross-data-center-firewall-policy
https://www.ctl.io/api-docs/v2/#firewall-policies-get-cross-data-center-firewall-policy-list
https://www.ctl.io/api-docs/v2/#firewall-policies-update-cross-data-center-firewall-policy

**Comment by jruckle** [comment]
@ldmberman - approved - this is this something you can do?
