### ISSUE TITLE
remove premium from code

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/clc-go-cli#55]
please remove all traces of premium storage from CLI.  its retired.  

@jruckle

**Comment by chrislittle** [comment]
@jruckle is this approved?  we need premium out of the CLI

**Comment by gavin-lai** [comment]
Any updates?  Thanks

**Comment by richardcase** [comment]
I'm looking at this now.

**Comment by richardcase** [comment]
I tested creating a server with a storage type of premium and the server was built. The storage type was actually provisioned as standard:

"DisplayName": "GB3CCTSMYSERV01",
        "GroupId": "b3945c669eb547a58abbe9b1531534a2",
        "Id": "gb3cctsmyserv01",
        "IsTemplate": false,
        "LocationId": "GB3",
        "Name": "GB3CCTSMYSERV01",
        "Os": "ubuntu14_64Bit",
        "OsType": "Ubuntu 14 64-bit",
        "Status": "active",
        **"StorageType": "standard",**
        "Type": "standard"

I'll continue to remove the 'premium' references from the cli.

**Comment by gavin-lai** [comment]
Hi Richard,
You are correct, premium option will have no effect on the build now.  It is just confusing for clients who know premium storage.
Thank you very much for your help.
Gavin

**Comment by richardcase** [comment]
I have made this code change and will let you know when a pull request has been made to make it available.
