### ISSUE TITLE
create site to site vpn api

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/clc-go-cli#56]
please add site to site vpn (including an example in the readme) v2 api to the CLI
@jruckle 

https://www.ctl.io/api-docs/v2/#networks-create-a-site-to-site-vpn
https://www.ctl.io/api-docs/v2/#networks-delete-a-site-to-site-vpn
https://www.ctl.io/api-docs/v2/#networks-get-site-to-site-vpns
https://www.ctl.io/api-docs/v2/#networks-update-a-site-to-site-vpn

**Comment by chrislittle** [comment]
@jruckle is this approved?

**Comment by jruckle** [comment]
@chrislittle yes approved @uzzz can you please add this to the list of enhancements?

**Comment by chrislittle** [comment]
@uzzz there appears to be some bug in the site to site vpn code.  I can't get the DiffieHelmanGroup to pass.  I have the syntax of diffieHelmanGroup but it seems the CLI is capitalizing the D when I run the command.  overall i'd love for case insensitivity to be part of this as having it case sensitive is painful

error:
```
Unknown option or argument: `DiffieHelmanGroup`
```

example:
```
clc site-to-site-vpn create --local "alias=CLC to NH,subnets=10.101.44.0/24" --remote "siteName=NH,deviceType=juniper srx100,address=73.4.199.84,subnets=192.168.1.0/24" --ipsec "encryption=aes128,hashing=sha1_96,protocol=esp,pfs=group2,lifetime=28800" --ike "encryption=aes128,hashing=sha1_96,diffieHelmanGroup=group2,preSharedKey=68C9EE96483B11E6B7431C14E8BF5E87,lifetime=28800,mode=main,deadPeerDetection=false,natTraversal=false,remoteIdentity=false"
```

**Comment by uzzz** [comment]
@chrislittle it actually was a typo: I wrote DiffieHe**ll**manGroup instead of DiffieHelmanGroup. Fixed now.

**Comment by chrislittle** [comment]
@uzzz i'm now seeing (removed passwords, usernames & token info)

```
2016/07/13 09:00:05 Creating new connection. Username: XXXXXXXX
2016/07/13 09:00:05 Sending request: POST /v2/authentication/login HTTP/1.1
Host: api.ctl.io
Clc-Alias:
Content-Type: application/json
User-Agent: clc-go-cli-2016-07-13-windows

{"Username":"XXXXXXXXXX","Password":"XXXXXXX"}
2016/07/13 09:00:05 Response received: HTTP/1.1 200 OK
Content-Length: 470
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Wed, 13 Jul 2016 12:58:42 GMT
Expires: -1
Pragma: no-cache
Strict-Transport-Security: max-age=31536000
Via: 1.1 VA1T3NLOADFE01
X-Served-By: VA1T3NWEB02CH

{"userName":"XXXXXX","accountAlias":"CCVA","locationAlias":"CA3","roles":["AccountAdmin"],"bearerToken":"XXXXXXXXXXXXXXXXXXXX"}
2016/07/13 09:00:05 Updating connection. Bearer: XXXXXXXXXXXXXXXXX, Alias: CCVA
2016/07/13 09:00:05 Sending request: POST /v2/siteToSiteVpn?account=CCVA HTTP/1.1
Host: api.ctl.io
Authorization: Bearer XXXXXXXXXXXXX
Clc-Alias: CCVA
Content-Type: application/json
User-Agent: clc-go-cli-2016-07-13-windows

{"Local":{"locationAlias":"CA3","Subnets":["10.101.44.0/24"]},"Remote":{"SiteName":"NH","DeviceType":"junipersrx100","Address":"73.4.199.84","Subnets":["192.168
.1.0/24"]},"Ipsec":{"Encryption":"aes128","Hashing":"sha1_96","Protocol":"esp","Pfs":"group2","Lifetime":28800},"Ike":{"Encryption":"aes128","Hashing":"sha1_96"
,"DiffieHelmanGroup":"group2","PreSharedKey":"68C9EE96483B11E6B7431C14E8BF5E87","Lifetime":"28800","Mode":"main","DeadPeerDetection":"false","NatTraversal":"false","RemoteIdentity":""}}
2016/07/13 09:00:07 Response received: HTTP/1.1 500 Internal Server Error
Content-Length: 36
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Wed, 13 Jul 2016 12:58:45 GMT
Expires: -1
Pragma: no-cache
Strict-Transport-Security: max-age=31536000
Via: 1.1 VA1T3NLOADFE01
X-Served-By: VA1T3NWEB02CH

{"message":"An error has occurred."}
Error occured while sending request to API. Status code: 500. Server says: An error has occurred.
```

I modified my code as I noticed alias must equal the DC location (i.e. CA3) from my last attempt.  It all looks right.  can you provide a working example in the readme?  

```
clc site-to-site-vpn create --local "alias=CA3,subnets=10.101.44.0/24" --remote "siteName=NH,deviceType=junipersrx100,address=73.4.199.84,subnets=192.168
.1.0/24" --ipsec "encryption=aes128,hashing=sha1_96,protocol=esp,pfs=group2,lifetime=28800" --ike "encryption=aes128,hashing=sha1_96,diffieHelmanGroup=group2,pr
eSharedKey=68C9EE96483B11E6B7431C14E8BF5E87,lifetime=28800,mode=main,deadPeerDetection=false,natTraversal=false,remoteIdentity=false"
```

**Comment by chrislittle** [comment]
@uzzz we also have to fix the term 'alias' in the code.  ALIAS is a totally different component of our stack.  ALIAS = a customers unique account alias.  it should be locationAlias in the code and the description should = Short code for a particular location (on the local side).  --account-alias if you look in the CLI code is for targeting specific accounts in a tree

**Comment by uzzz** [comment]
Hmm... Maybe it's an API issue? Just performed following steps:
1. Crated site-to-site VPN from ctl.io
2. Run `clc site-to-site-vpn list` to get VPN json data
3. Deleted site-to-site VPN from step 1)
4. Tried to POST against an API using CURL with data from step 2) (data was modified as far as GET and POST requests a bit different: for example GET does have an `id` field, but doesn't have `preSharedKey`, but most of the fields are the same)

And got 500 error. Can we check with API team to look through logs or something like that? It still could be a request issue, but anyway, I believe a server should respond with 4xx and return error message explaing what's wrong in that case.

As for alias it's a good catch, thanks, I'll fix it.

**Comment by chrislittle** [comment]
@jruckle see above.  how do you want to handle issues for the dev teams who need support from platform to look into api issues?  is there an established approach for the teams?  or do I need to shuffle this through personally @gavin-lai @uzzz

**Comment by chrislittle** [comment]
ticket opened @uzzz (you were cc'd)
https://t3n.zendesk.com/agent/tickets/1291129

**Comment by uzzz** [comment]
So according to Scott Densmore my initial typo was accidentally correct :)

**Comment by chrislittle** [comment]
thx @uzzz i'll watch for the new release once its ready.  did you also see my pull request to update the readme as it points to super old releases in the links

**Comment by chrislittle** [comment]
tested fully
