### ISSUE TITLE
Bash Errors Due to the '~/.bash_completion' Directory

### ISSUE THREAD

**Issue by casrep** [CenturyLinkCloud/clc-go-cli#57]
There's a small issue the occurs after `install_autocompletion` script creates the `.bash_completion` directory in my home folder on Linux. When opening new terminal sessions, it presents the error below:

```
bash: .: /home/derek/.bash_completion: is a directory
bash: .: /home/derek/.bash_completion: is a directory
```

I'm not overly familiar with the hierarchy of profile scripts that are sourced when a session starts, but there's clearly a conflict. Bash is expecting a script or executable where it finds a directory. I solved this by not running `install_autocompletion`.

The script adds this line to the user's `.bashrc` file:

```
source ~/.bash_completion/clc"
```

Instead, I added this line:

```
source ~/bin/clc_cli/autocomplete/bash_autocomplete
```

They're the same script. It should still work because they don't seem to use relative paths (except those relative to `~`). Another option could be for `install_autocompletion` to copy the `bash_completion` script to `~/.clc`, then have `.bashrc` source it from that directory.

Granted, this could just be a quirk of my installation since I haven't seen any other issues submitted for this, but it could be a nice workaround for others like me.

**Comment by uzzz** [comment]
@casrep Hi! Thanks for the feedback. What Linux distribution do you use?

**Comment by casrep** [comment]
Sorry for the delay.
```
Linux bunsenlabs 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

Distributor ID:	BunsenLabs
Description:	BunsenLabs GNU/Linux 8.4 (Hydrogen)
Release:	8.4
Codename:	bunsen-hydrogen
```

I'm going to test on my Ubuntu install to see if I see the same thing.

**Comment by casrep** [comment]
Seeing the same thing on Ubuntu. Here's the system info.

```
Linux battsta-trusty 3.19.0-58-generic #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty

GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
```

Here's the bash version on my BunsenLabs system in my last message.

```
GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)
```

**Comment by uzzz** [comment]
Yes, there was an issue. Most Linux distributions assume that `~/.bash_completion` is a file with user-defined completions, not a directory. Fixed ./install_autocomplete, will be delivered in next release.
