### ISSUE TITLE
Autocomplete Issue - .bash_profile Not Utilized

### ISSUE THREAD

**Issue by casrep** [CenturyLinkCloud/clc-go-cli#59]
The new autocomplete script changes adding a source to the .bashrc file to adding a source to the non-existent .bash_profile file. Which ends up creating the file and making it look like the below:

```

[[ -s /home/work/.bash_completion.d/clc ]] && source /home/work/.bash_completion.d/clc
```

Since .bashrc is used more commonly, especially on Debian-based systems, perhaps a fallback option of adding the line to .bashrc would be appropriate?

**Comment by uzzz** [comment]
Are you sure @casrep ? From what I can see it add this line to .bashrd on linux and to .bash_profile on Mac OS X

**Comment by casrep** [comment]
That makes sense. I must have grabbed the Mac version. I just blew the binary and downloaded again making sure I chose the right one. It seems to be working.

Sorry for the false issue.
