### ISSUE TITLE
Error updating disks using CLI

### ISSUE THREAD

**Issue by gavin-lai** [CenturyLinkCloud/clc-go-cli#69]
Hi CLI team,
I am running into error when I try the following:
clc server update --server-name ca2ccvaweb01 --disks "id=0:0,SizeGB=1 id=0:1,SizeGB=2 ID=0:2,SizeGB=20"
Unknown option or argument: `Id`.
I check the options in the API docs and tried using "disk-id" etc to test the command.  Is there any pointer for this command or there is an issue with changing the disk size?
Thanks
Gavin

**Comment by richardcase** [comment]
Hi Gavin,

I had a look at this and its not the most intuitive. To update the disks for a server you have to specify what disks to keep and what to do. 

When changing the amount of space (i.e. to increase the size of a disk) you create a request that lists all existing disks as 'keep' but you specify the new size (in GB) of the disk you want to expand. I found this easier to do when using JSON for the command line parameters.  An example is:

`server update '{"ServerId": "gb3eusetst02","Disks" : {"Keep" : [{ "DiskId": "0:0", "SizeGB": 1},{ "DiskId": "0:1", "SizeGB": 2},{ "DiskId": "0:2", "SizeGB": 22}]}}' `

In this example my server has 3 disks already (as can be seen from clc server get --server-id gb3eusetst02) so include all 3 disks and i just increased SizeGB for the disk 0:2.

There was a bug in the code as well and i have fixed this. So this should work in the next release.

Let me know if you have any questions.

**Comment by gavin-lai** [comment]
Hi Richard,
That sounds good, it does require all the disks information which is confusing.
Thanks
Gavin

---
Gavin Lai | Sr. Cloud Solutions Architect
CenturyLink Cloud
Phone: 647-745-7898
Email: gavin.lai@ctl.io
www.ctl.io<http://www.centurylinkcloud.com/>
[Description: Machine generated alternative text: CenturyLink]<http://www.ctl.io/>

**Comment by gavin-lai** [comment]
Still getting error running the new command: PS C:\Users\peter_000\Documents\tools\clc> .\clc.exe server update '{"ServerId": "va1pmta00000003","Disks" : {"Keep" : [{ "Id": "0:0", "SizeGB": 1},{ "Id": "0:1", "SizeGB": 2},{
"Id": "0:2", "SizeGB": 22}]}}'

{ServerId: va1pmta00000003,Disks : {Keep : [{ Id: 0:0, SizeGB: 1},{ Id: 0:1, SizeGB: 2},{ Id: 0:2, SizeGB: 22}]}} is neither a valid JSON object nor a valid object in a=b,c=d.. format.
PS C:\Users\peter_000\Documents\tools\clc>
