### ISSUE TITLE
Bare Metal updates

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/clc-go-cli#75]
couple of items.
1.  the --os-type used for bare metal skus are missing Ubuntu 14 & Windows 2012 R2 DC Edition.  Might be worth cleaning up the text and making sure no case sensitivity.

```
Only required for bare metal servers. Specifies the OS to provision with the bare metal server. Currently, the only supported OS types are redHat6_64Bit, centOS6_64Bit, windows2012R2Standard_64Bit. Ignored for standard and hyperscale servers.
```
1.  the --configuration-id seems to be unknown.  it seems as though the v2 api says it should be in the get deployment capabilities but the CLI command doesn't output it.  i.e. running 

```
clc datacenter get-deployment-capabilities --data-center NY1
```

**Comment by chrislittle** [comment]
get bare metal details using this:  https://www.ctl.io/api-docs/v2/#data-centers-get-data-center-bare-metal-capabilities . seems like a separate call

**Comment by chrislittle** [comment]
Configuration|ConfigurationID
---------------|------------------
4 core, 16 GB RAM, 2x 1TB Raw HDD|529e2592a3e640a7c2617b5e8bc8feaed94eac22
12 core, 64 GB RAM, 4x 2TB Raw HDD|f24b18ba2ce23657657444601649c7b8b7f9b60c
20 core, 128 GB RAM, 6x 2TB Raw HDD|8057e3629403e92d6693352ad17a807dc8970aef
24 core, 128 GB RAM, 1x 960GB Raw SSD|331afd25f49e10187c9095a33bd16209e013a56f
24 core, 128 GB RAM, 1x 3.84TB Raw SSD|44ed64b3174dc99f6f549b3707eefcc58fd701de
24 core, 512 GB RAM, 1x 3.84TB Raw SSD|7f6a073eb8e13626ee01c1ab5e698cf1c25ca073
20 core, 256 GB RAM, 2x800GB SSD & 12x2TB HDD|43e0a50bf7ab9e80c493b1c8bf5da75dfba3f7e1
16 core, 256 GB RAM, 2x800GB SSD & 4x4TB HDD|2516e341b960652f01563933d72523d9c222a437

**Comment by chrislittle** [comment]
To further add it seems creating bare metal servers needs a modification as when creating in the CLI it wants template-names, CPU etc when those are ignored anyway.  a simple build should be 

clc create server --name X --group-name --network-name X --type baremetal --configuration-id x --os-type.... then datacenter and account alias switches as needed.

**Comment by richardcase** [comment]
I recently added get baremetal capabilities to the GO SDK: https://github.com/CenturyLinkCloud/clc-sdk/commit/733135050ccaaa7d2857845466e01958f9d6b096.

If creating a server using the CLI we should get the baremetal capabilities before issuing the actual create API call, we can then do validation checks in the CLI and give helpful error messages.

**Comment by richardcase** [comment]
I have implemented the 'get-baremetal-capabilities' command in the cli. 

For the "server create" i propose the following:
- The description for 'configuration-id' is modified to state that the list of valid ids can be obtained from the 'get-baremetal-capabilities' command
- The description for 'os-type' is changed to remove any references to specific operating systems. Instead we say that 'get-baremetal-capabilities' can be used to get the list of supported OSes
- We modify the 'CreatReq' struct to remove some of the 'valid:"required"' tags and instead move the checks to the Validate method and make it dependent on the set server type.

@chrislittle does that sound ok and would it resolve this issue?

**Comment by chrislittle** [comment]
sounds good @richardcase
