### ISSUE TITLE
Multiple commands do not work on windows

### ISSUE THREAD

**Issue by inge4pres** [CenturyLinkCloud/clc-go-cli#84]
Hi,

I'm on Windows, I fetched release [2016-07-21](https://github.com/CenturyLinkCloud/clc-go-cli/releases) installed in my PATH and getting this error when running the CLI

`clc: error: argument command: invalid choice: 'login' (choose from 'accounts', 'users', 'servers', 'groups', 'billing', 'networks', 'queue', 'blueprints')`

I configured the credentials with %HOME%/clc/config.yml file but I'm not able to run any command from the CLI, getting another error with the suggested commands

`x Exiting due to error: 'module' object has no attribute 'V1_API_KEY'`

Any idea on what's going on?
Thank you

**Comment by richardcase** [comment]
Could you supply the command line (with any sensitive data removed) you using when executing CLC?

**Comment by inge4pres** [comment]
Sure
`clc login --user my.user.name.for.ctl.io --password my.password.ctl.io

usage: clc [-h] [--cols [COL [COL ...]]] [--config CONFIG] [--v1-api-key KEY]
           [--v1-api-passwd PASSWORD] [--v2-api-username USERNAME]
           [--v2-api-passwd PASSWORD] [--async] [--quiet] [--verbose]
           [--format {json,table,text,csv}]
           {accounts,users,servers,groups,billing,networks,queue,blueprints}
           ...
clc: error: argument command: invalid choice: 'login' (choose from 'accounts', 'users', 'servers', 'groups', 'billing', 'networks', 'queue', 'blueprints')
`

`$ clc --v2-api-username auniquekeygeneratedfromwebinterface --v2-api-passwd thekeypa$$w0rd groups list

x Exiting due to error: 'module' object has no attribute 'V1_API_KEY'`

**Comment by richardcase** [comment]
Thanks 😄

I'll have a look and get back to you.

**Comment by richardcase** [comment]
Could you try the login command with the [latest release](https://github.com/CenturyLinkCloud/clc-go-cli/releases/tag/v1.1.0-rc.1)?

This is a pre-release version. I just ran the the login command on Windows with this version without issue:

![windowscli](https://cloud.githubusercontent.com/assets/198425/20104285/5445589c-a5c5-11e6-819f-026bd99a9537.png)

**Comment by inge4pres** [comment]
```
$ clc login --user francesco.gualazzi.pp --password pcKBT6q8IW0djqB2
usage: clc [-h] [--cols [COL [COL ...]]] [--config CONFIG] [--v1-api-key KEY]
           [--v1-api-passwd PASSWORD] [--v2-api-username USERNAME]
           [--v2-api-passwd PASSWORD] [--async] [--quiet] [--verbose]
           [--format {json,table,text,csv}]
           {accounts,users,servers,groups,billing,networks,queue,blueprints}
           ...
clc: error: argument command: invalid choice: 'login' (choose from 'accounts', 'users', 'servers', 'groups', 'billing', 'networks', 'queue', 'blueprints')

```

**Comment by chrislittle** [comment]
also, what operating system are you using?  I can also try to duplicate.

**Comment by inge4pres** [comment]
LOL I found out why!
```
$ which clc
/c/Python27/Scripts/clc
```

**Comment by richardcase** [comment]
With the new rc-1 version you can get version information by using:

`clc version`

If this command isn't available you know you are using an older version on the CLI.

Can we close this issue?

**Comment by chrislittle** [comment]
awesome!  do you have the python CLC CLI/SDK also loaded?

**Comment by inge4pres** [comment]
Yeah I'll be hard-testing all CLC software for 1-2 weeks from yesterday :)

**Comment by chrislittle** [comment]
feel free to hit us up on new issues if required.
