### ISSUE TITLE
Update Server Public IP: Specifying Multiple Ports

### ISSUE THREAD

**Issue by casrep** [CenturyLinkCloud/clc-go-cli#89]
The documentation isn't clear on how to specify multiple ports when updating a server's public IP with `server update-public-ip-address`. It seems like only one can be specified in each query. This is a problem since the command overwrites the current port configuration for the server instead of appending to it.

**Comment by richardcase** [comment]
I agree the documentation isn't clear on how you specify an array of items, ports in this case. This has also come up when specifying source restrictions.

To specify multiple ports you need to do the following:

`clc server update-public-ip-address --server-name MyServerName --public-ip xxx.xxx.xxx.xxx --ports "port=80,protocol=tcp" "port=443,protocol=tcp"`

Basically you quote each item in the array and then separate items with a space. I'll add this example to the README.

**Comment by chrislittle** [comment]
@gavin-lai can you update your CLI guide in the KB to show an example of this and the multiple CIDR array so at least folks have an example, with that + the readme example that should help on these array items.

**Comment by richardcase** [comment]
Closing as this is will be documented in the KB and a sample has been added to the README.md

**Comment by casrep** [comment]
That's good info. Thank you.
